# Generated by Django 4.1.6 on 2023-02-12 14:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='*')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Category')),
                ('price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Price')),
                ('priceCurrency', models.CharField(blank=True, max_length=20, verbose_name='Currency')),
                ('pricePerMeter', models.CharField(blank=True, max_length=100, verbose_name='Price Per Meter')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('offerId', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Offer Id')),
                ('contacts', models.BooleanField(default=False, verbose_name='Contacts')),
                ('body', ckeditor.fields.RichTextField(blank=True, verbose_name='Body')),
                ('contact_body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='ContactBody')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('source', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('url', models.URLField(blank=True, max_length=400, null=True, verbose_name='Image url')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.post')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(blank=True, default=False, verbose_name='Status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date ')),
                ('post_id', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
    ]
