# Generated by Django 4.1.4 on 2023-01-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contacts',
            field=models.BooleanField(default=False, verbose_name='Contacts'),
        ),
    ]
