# Generated by Django 4.1.5 on 2023-02-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_postimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.URLField(blank=True, default='https://s.backendservices.ru/j/nq3BrPnwpXoil3BTdzdtu9Qy.658f34c2/dom/p/71/08/710883/ad1ff5a3fa.jpg', max_length=300),
        ),
    ]
