# Generated by Django 4.0.6 on 2023-02-06 08:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contact_id_alter_post_id_alter_postimages_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact_body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='ContactBody'),
        ),
    ]
