# Generated by Django 4.0.6 on 2023-02-06 09:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_contact_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='ContactBody'),
        ),
    ]
